# Generated by Django 5.1.1 on 2024-10-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsportal',
            name='quantity_pallet_code',
            field=models.CharField(default='UF_CRM_0000000000', help_text='Код поля количество паллет в сделке', max_length=30, verbose_name='Код поля количество паллет'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='tonnage_code',
            field=models.CharField(default='UF_CRM_0000000000', help_text='Код поля тоннаж в сделке', max_length=30, verbose_name='Код поля тоннаж'),
        ),
    ]
