# Generated by Django 5.1.1 on 2024-09-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrow',
            name='PRODUCT_DESCRIPTION',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
    ]
