# Generated by Django 5.1.1 on 2024-10-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_package_productrow_quantity_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='WEIGHT',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Вес'),
        ),
    ]
