# Generated by Django 5.1.1 on 2024-10-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_package_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrow',
            name='XML_ID',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='XML_ID'),
        ),
    ]
